// Generated by: gen
// TypeWriter: slice
// Directive: +gen on *LinkExt

package netlinkext

// LinkExtSlice is a slice of type *LinkExt. Use it where you would use []*LinkExt.
type LinkExtSlice []*LinkExt

// Where returns a new LinkExtSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv LinkExtSlice) Where(fn func(*LinkExt) bool) (result LinkExtSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
